### ISSUE TITLE
Adicionar funcionalidades/relatórios

### ISSUE THREAD

**Issue by jozerdj** [falcaopetri/fisio#2]
Adicionar as seguintes funcionalidades:

1. Consultar histórico do paciente (buscar todas as consultas de um paciente)
2. Consultar histórico de avaliações por lesão
3. Consultar histórico de avaliações por paciente
4. Consultar pacientes por fisioterapeuta

**Comment by falcaopetri** [comment]
- [Grails: filter data in a Grails table dynamically](https://stackoverflow.com/questions/3105021/grails-filter-data-in-a-grails-table-dynamically)
- [Grails: How do I make my page load a filter when the page loads?](https://stackoverflow.com/questions/3150155/grails-how-do-i-make-my-page-load-a-filter-when-the-page-loads)
- [I have a bunch of data and I need a data filter using Grails](https://stackoverflow.com/questions/3096572/i-have-a-bunch-of-data-and-i-need-a-data-filter-using-grails)
