### ISSUE TITLE
Criar Combo Boxes para recursos estáticos que se repetem

### ISSUE THREAD

**Issue by jozerdj** [falcaopetri/fisio#4]
Criar combo boxes para os seguintes atributos.

Classe - **Atributo** - [Valores]:

Relatorio - **status** - ["Evolução", "Estagnação", "Involução"]
Ficha - **status** - ["Tratamento não iniciado", "Em tratamento", "Tratamento concluído"]
Ficha - **gravidade** - ["Leve", "Mediana", "Grave", "Gravissima"]
Paciente - **estadoCivil** - ["Solteiro", "Casado"]
Avaliacao - **tipoTratamento** - ["Cirurgico", "Conservador"]

**Comment by falcaopetri** [comment]
https://stackoverflow.com/a/3749015
